name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: install and deploy 
        run: ./.github/scripts/deploy-circleci.sh
      # - run: npm i yarn
      # - run: yarn
      # - run: yarn add --dev gh-pages
      # - run: git config --global user.email "455711093@qq.com"
      # - run: git config --global user.name "lihqi"
      # - run: yarn run deploy
    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@master
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: build
    #     BUILD_SCRIPT: npm install && npm run build
